# Generated by Django 5.2.17 on 2026-08-18 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name (e.g., Haircut, Beard Trim)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed service description', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Service price in dollars', max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Service duration in minutes (used for slot calculation)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently available for booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'booking_service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Staff member biography and specializations', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Whether this staff member is available for booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(help_text='Services this staff member can provide', related_name='staff_members', to='booking.service')),
                ('user', models.OneToOneField(help_text='Link to staff user account', limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'db_table': 'booking_staff_profile',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='Date of the appointment')),
                ('start_time', models.TimeField(help_text='Appointment start time')),
                ('end_time', models.TimeField(help_text='Appointment end time (calculated from service duration)')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CONFIRMED', help_text='Current status of the appointment', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from customer or staff', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer who booked the appointment', limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Service being provided', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='booking.service')),
                ('staff', models.ForeignKey(help_text='Staff member assigned to the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.staffprofile')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'booking_appointment',
                'ordering': ['-appointment_date', '-start_time'],
                'indexes': [models.Index(fields=['appointment_date', 'status'], name='booking_app_appoint_70b463_idx'), models.Index(fields=['customer', 'status'], name='booking_app_custome_78f1c6_idx'), models.Index(fields=['staff', 'appointment_date'], name='booking_app_staff_i_b8901d_idx')],
                'unique_together': {('staff', 'appointment_date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField(help_text='Working start time')),
                ('end_time', models.TimeField(help_text='Working end time')),
                ('staff', models.ForeignKey(help_text='Staff member this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='booking.staffprofile')),
            ],
            options={
                'verbose_name': 'Working Hours',
                'verbose_name_plural': 'Working Hours',
                'db_table': 'booking_working_hours',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('staff', 'day_of_week')},
            },
        ),
    ]
